const LETRAS = 'ABCDEFGHIJKLMNÑOPQRSTUVWXYZ';
// Recordar que los string son "como un array inmutable"; 
const palabras = [
  'QUIZAS',
  'EXQUISITO',
  'ZARZAMORA',
  'OXIGENO',
  'KIOSCO',
  'ZORRO',
  'SAXOFON',
  'QUILATE',
  'EXHUMAR',
  'QUIMERA',
  'ELECTRODOMESTICO',
  'HIPOTENUSA',
  'PARALELEPIPEDO',
  'ANTICONSTITUCIONAL',
  'METAMORFOSIS',
  'INCONSTITUCIONALIDAD',
  'ABERRACION',
  'PROCASTINACION',
  'LUZ',
  'JAZZ',
  'OJAL',
  'FAX',
  'QUIZ',
  'ZEN',
  'VOZ',
  'TIRANOSAURIO',
  'ARRASTRAR',
  'CALLEJERO',
  'ACCEDER',
  'ROLLO',
  'FALLO',
  'ACENTUAR',
  'GUILLOTINA',
  'DERRAMAR',
  'ALLANAR',
  'ATRACCION',
  'CREPUSCULO',
  'TERMODINAMICA',
  'QUIRURGICO',
  'GEOTERMIA',
  'HIDROELECTRICO',
  'SINAPSIS',
  'BACTERIOLOGIA',
  'ANALISIS',
  'ENDOCRINO',
  'HEMATOMA',
  'NEURONA',
  'SUSHI',
  'PIZZA',
  'SIERRA',
  'ZIGZAG', 
  'GLICERINA'
]
const NUMERO_PALABRAS = palabras.length;
console.log('Tenemos', NUMERO_PALABRAS, 'para jugar')
